// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXX_A27zxSFPCZ_0-fhQQVIx9ZCbsAVLU',
    appId: '1:387888832806:web:f3993ed1d01a89c205e1e7',
    messagingSenderId: '387888832806',
    projectId: 'notes-application-8a8bf',
    authDomain: 'notes-application-8a8bf.firebaseapp.com',
    storageBucket: 'notes-application-8a8bf.appspot.com',
    measurementId: 'G-03BL4TKYK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjzNqXm3e1O6GTilR8jNyEvlK8PIs61dQ',
    appId: '1:387888832806:android:5ea7706ff10b179505e1e7',
    messagingSenderId: '387888832806',
    projectId: 'notes-application-8a8bf',
    storageBucket: 'notes-application-8a8bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkwJ7oSUeiELdtSta7Fds40u1daG_ssJ8',
    appId: '1:387888832806:ios:c39fb41708ac4b6a05e1e7',
    messagingSenderId: '387888832806',
    projectId: 'notes-application-8a8bf',
    storageBucket: 'notes-application-8a8bf.appspot.com',
    iosBundleId: 'com.example.todoList',
  );
}
